### PR TITLE
5 integration test

### PR DESCRIPTION
**Pull request by philboeselager**

### CODE REVIEW

**Review by blackwinter — COMMENTED** [review]
Regarding a061ee8: The [documentation](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables) says "do not depend on this [USER] value". I'd suggest going for `CI` or `TRAVIS` instead.

**Comment by blackwinter** [comment]
Do you object to [this commit](https://bitbucket.org/hbz/limetrans/commits/9953519)? I'd rather not have my test output fill dozens of screens...

**Comment by blackwinter** [comment]
Why did you implement each field report test as an individual test class? Wouldn't a single (parameterized) `DE836FieldReportTest` be much simpler?

**Comment by blackwinter** [comment]
Would it make sense to specify thresholds as a percentage, i.e. relative to the number of reference documents?

**Comment by philboeselager** [comment]
> Why did you implement each field report test as an individual test class? Wouldn't a single (parameterized) DE836FieldReportTest be much simpler?

You mean using JUnit4's `@Rule` ? That would make it impossible to run the single test cases separately, wouldn't it?

**Comment by philboeselager** [comment]
> Would it make sense to specify thresholds as a percentage, i.e. relative to the number of reference documents?

Sure, there are dozens of possibilities to enhance these tests. I feel like we should not spend too much work in it for now, as testing against the existing toolbox ground truth is just a temporary test case. I would suggest to think about these enhancements later, when we re-organize the testing as a kind of regression test framework.

**Comment by blackwinter** [comment]
> You mean using JUnit4's `@Rule`?

No, I meant with `@Parameters` just like you have now, only with multiple values on a single class instead of a single value on multiple classes.

> That would make it impossible to run the single test cases separately, wouldn't it?

True, but do we need it? And even if we do, aren't there other ways to achieve this without the amount of code duplication?

**Comment by blackwinter** [comment]
> I feel like we should not spend too much work in it for now

Ok, that's hard to argue with...

I'll amend 389bcce to apply the change to `src/test/resources/log4j2.xml` instead of `src/main/resources/log4j2.xml`, accounting for the need to log to the console on Travis, and then merge the pull request.

**Comment by philboeselager** [comment]
> No, I meant with @Parameters just like you have now, only with multiple values on a single class instead of a single value on multiple classes.

Makes perfect sense.

> True, but do we need it?

We would survive without it. Nevertheless, I like it.

> And even if we do, aren't there other ways to achieve this without the amount of code duplication?

I don't know, yet. I'm going to refactor it the way you've described, anyways.

**Comment by blackwinter** [comment]
Closes #5.

**Pull request merged**
