### PR TITLE
Future proof metafacture 4

### PR DESCRIPTION
**Pull request by blackwinter**

### CODE REVIEW

**Comment by ghost** [comment]
That's a big help, thanks! :)
One tiny little thing though: Sometimes i get 
`[...]expected:<...ITERAL(=[...]`
as output, whereas this
`[...]expected:<LITERAL(=[...]`
looks more like the intendet output.
The only regularity i could find is, that is appears to be happening every time i add something at the end of a field (see examples below). 
```
<2>/xbib[]/ expected:<...ITERAL(uid=(DE-836)2[3])> but was:<...ITERAL(uid=(DE-836)2[])>
<2>/xbib[]/ expected:<LITERAL(uid=(DE-836)[3])> but was:<LITERAL(uid=(DE-836)[2])>
<2>/xbib[]/ expected:<LITERAL(uid=(DE-836)[3]2)> but was:<LITERAL(uid=(DE-836)[]2)>
<2>/xbib[]/ expected:<LITERAL(uid=[]DE-836)2)> but was:<LITERAL(uid=[(]DE-836)2)>
<2>/xbib[]/ expected:<LITERAL(uid=[1]DE-836)2)> but was:<LITERAL(uid=[(]DE-836)2)>
<2>/xbib[]/ expected:<LITERAL(uid=[1](DE-836)2)> but was:<LITERAL(uid=[](DE-836)2)>
```

**Comment by blackwinter** [comment]
The diff output is truncated after a certain [length limit](/junit-team/junit4/blob/master/src/main/java/org/junit/ComparisonFailure.java#L18).

**Comment by ghost** [comment]
<2>/xbib[]/ expected:<LITERAL(uid=(DE-836)2[3])> but was:<LITERAL(uid=(DE-836)2[])>
and 
<2>/xbib[]/ expected:<LITERAL(uid=(DE-836)[3]2)> but was:<LITERAL(uid=(DE-836)[]2)> 
would be the same length?

**Comment by blackwinter** [comment]
Yes, it's the same diff length, but not the same _context_ length, which is the relevant one here (or, more specifically, prefix length and suffix length). Anyway, I'm working on a - hopefully - more helpful diff output. Hang tight.

**Comment by blackwinter** [comment]
I've changed the error message to indicate the mismatch type and print both expected and actual entity paths. Paths include event type, name, and value, as well as record number and array position. Alas, diff output is gone; let me know if it's needed.

In addition to that, missing or unexpected events are printed in full; let me know if it's too verbose.

**Comment by ghost** [comment]
I like this a lot! :)
All the information you need in a nice easy to read output.

**Review by philboeselager — APPROVED** [review]

**Pull request merged**
